### PR TITLE
change import of ZHAGateway from zha.core

### LINKED ISSUE #237: Setup failed with 2024.8.0b0
with latest HA Beta (2024.8.0b0) I am getting the following error:

```
Logger: homeassistant.setup
Quelle: setup.py:333
Erstmals aufgetreten: 00:44:30 (1 Vorkommnisse)
Zuletzt protokolliert: 00:44:30

Setup failed for custom integration 'zha_toolkit': Unable to import component: No module named 'homeassistant.components.zha.core'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/zha_toolkit/__init__.py", line 7, in <module>
    from homeassistant.components.zha.core.gateway import ZHAGateway
ModuleNotFoundError: No module named 'homeassistant.components.zha.core'
```

### PR DESCRIPTION
**Pull request by ChristophCaina**
fix #237

### CODE REVIEW

**Comment by CordoWEB** [comment]
If this works ... do not forget to say thank you to the author ... me :)

**Comment by ChristophCaina** [comment]
sure, thanks a lot @CordoWEB

**Comment by mdeweerd** [comment]
I like to keep the code backward compatible.

I guess the easiest approach here is to do it with a `try` construct: load the new one first and if that does not work, try the old path.

**Comment by mdeweerd** [comment]
Also, using "import ... as .ZHAGateway" should avoid the issue reported by the tools.

**Comment by ChristophCaina** [comment]
I'll change it and see, if it is working (but I cannot test the exception case)

**Comment by CordoWEB** [comment]
You can also test HA version : 

`
if parse_version(HA_VERSION) >= parse_version("2024.8"):
    from homeassistant.components.zha import Gateway as ZHAGateway
else
    from homeassistant.components.zha.core.gateway import ZHAGateway
`

**Comment by mdeweerd** [comment]
Thank you @CordoWEB and @ChristophCaina .  It's released in 1.1.12

**Pull request merged**
